In [50]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import recall_score, precision_score, roc_auc_score, confusion_matrix

In [5]:
df = pd.read_csv("/content/credit_risk_dataset.csv")

In [11]:
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [10]:
df = df.reset_index(drop=True)

In [12]:
df.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  object
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object
 5   loan_grade                  32581 non-null  object
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB

In [42]:
df = df.dropna()

In [43]:
x = df.drop(columns= ['loan_status','person_home_ownership','loan_intent','loan_grade','cb_person_default_on_file'])
y = df['loan_status']

In [44]:
x.info()
y.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28638 entries, 0 to 32580
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  28638 non-null  int64
 1   person_income               28638 non-null  int64
 2   person_emp_length           28638 non-null  float64
 3   loan_amnt                   28638 non-null  int64
 4   loan_int_rate               28638 non-null  float64
 5   loan_percent_income         28638 non-null  float64
 6   cb_person_cred_hist_length  28638 non-null  int64
dtypes: float64(3), int64(4)
memory usage: 1.7 MB
<class 'pandas.core.series.Series'>
Index: 28638 entries, 0 to 32580
Series name: loan_status
Non-Null Count  Dtype
--------------  -----
28638 non-null  int64
dtypes: int64(1)
memory usage: 447.5 KB

In [45]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [46]:
print("x_train")
display(x_train)
print(f"--------------------------------")
print("x_test")
display(x_test)
print("--------------------------------")
print("y_train")
display(y_train)
print("--------------------------------")
print("y_test")
display(y_test)
print("--------------------------------")

x_train

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length
14324,25,105000,2.0,9600,11.71,0.09,3
5698,23,150000,3.0,5000,10.65,0.03,2
22936,34,35000,1.0,8000,6.17,0.23,9
23963,31,68000,15.0,13600,7.88,0.20,9
5750,26,25300,2.0,5400,16.02,0.21,2
...,...,...,...,...,...,...,...
24543,28,74000,12.0,5450,12.67,0.07,6
6202,23,27000,6.0,6000,11.66,0.22,3
991,22,24000,1.0,6000,12.68,0.25,4
17959,30,225000,2.0,25000,12.42,0.11,10
26892,33,117000,17.0,20000,6.17,0.17,6

--------------------------------
x_test

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length
24777,27,75400,3.0,6000,7.74,0.08,9
18341,33,53004,0.0,20000,13.04,0.38,10
14584,26,110000,3.0,4000,6.92,0.04,2
23814,29,60000,11.0,6000,15.27,0.10,10
20906,28,66725,3.0,9000,16.29,0.11,9
...,...,...,...,...,...,...,...
27436,33,140000,8.0,8000,5.79,0.06,6
9169,26,16120,2.0,5000,11.58,0.31,3
17987,34,204000,0.0,16000,11.83,0.08,5
3532,22,37000,6.0,7500,10.95,0.20,2
24305,28,71007,4.0,25000,18.62,0.35,7

--------------------------------
y_train

14324    0
5698     0
22936    0
23963    0
5750     1
        ..
24543    0
6202     0
991      0
17959    0
26892    0
Name: loan_status, Length: 22910, dtype: int64

--------------------------------
y_test

24777    0
18341    1
14584    0
23814    1
20906    1
        ..
27436    0
9169     1
17987    0
3532     0
24305    0
Name: loan_status, Length: 5728, dtype: int64

--------------------------------

In [47]:
model = LogisticRegression(max_iter=1000)
model.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [51]:
y_pred = model.predict(x_test)
y_prob = model.predict_proba(x_test)[:,1]

In [53]:
cm = confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = cm.ravel()

print("True Negative:", tn)
print("False Positive:", fp)
print("False Negative:", fn)
print("True Positive:", tp)

True Negative: 4245
False Positive: 198
False Negative: 791
True Positive: 494

In [ ]:
recall = recall_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_prob)

print(recall, precision, auc)